config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  authenticated :user, ->(user) { user.admin? } do
    mount Delayed::Web::Engine, at: '/jobs'
  end
  get '/auth/:provider/callback', to: 'connections#create'
  resources :connections, only: [:destroy]
  get '/auth/failure', to: 'connections#omniauth_failure'

  devise_for :users, controllers: { registrations: 'registrations' }
  get 'pages/home'
  root'pages#home'
  get 'dashboard' => 'pages#dashboard'
  resources :posts do
    member do
      put :cancel
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/connection.rb
# frozen_string_literal: true

class Connection < ApplicationRecord
  belongs_to :user

  def self.create_from_omniauth(auth_hash)
    create(
      provider: auth_hash.provider,
      oauth_token: auth_hash.credentials.token,
      secret: auth_hash.credentials.secret
    )
  end
end

app/models/post.rb
# frozen_string_literal: true

class Post < ApplicationRecord
  belongs_to :user
  validates :content, length: { in: 10..140 }
  validates :scheduled_at, presence: true
  after_create :schedule
  # validates_datetime :scheduled_at, on: :create, on_or_after: Time.zone.now

  def to_twitter
    client = Twitter::REST::Client.new do |config|
      config.access_token        = user.twitter.oauth_token
      config.access_token_secret = user.twitter.secret
      config.consumer_key        = ENV['TWITTER_KEY']
      config.consumer_secret     = ENV['TWITTER_SECRET']
    end
    client.update(content)
  end

  def display
    unless state == 'cancel'
      to_twitter if twitter == true
      update_attributes(state: 'posted')
    end
  rescue StandardError => e
    update_attributes(state: 'posting error', error: e.message)
  end

  def schedule
    ScheduleJob.set(wait_until: scheduled_at).perform_later(self)
    update_attributes(state: 'scheduled')
  rescue StandardError => e
    update_attributes(state: 'scheduling error', error: e.message)
  end
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates_presence_of :time_zone

  has_many :connections, dependent: :destroy
  has_many :posts, dependent: :destroy

  def twitter
    connections.where(provider: 'twitter').first
  end

  def facebook
    connections.where(provider: 'facebook').first
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  around_action :user_time_zone, if: :current_user

  private

  def user_time_zone(&block)
    Time.use_zone(current_user.time_zone, &block)
  end
end

app/controllers/connections_controller.rb
class ConnectionsController < ApplicationController
  before_action :set_connection, only: [:destroy]

  def create
    connection = current_user.connections.create_from_omniauth(auth_hash)
    if connection.save
      redirect_to dashboard_path, notice: 'connnected'
    else
      redirect_to dashboard_path, notice: 'something went wrong'
    end
  end

  def omniauth_failure
    binding.pry
    redirect_to dashboard_path, notice: 'Something went wrong.'
  end

  def destroy
    @connection.destroy
    redirect_to dashboard_path, notice: 'connection destroyed'
  end

  private

  def set_connection
    @connection = Connection.find(params[:id])
  end

  def auth_hash
    request.env['omniauth.auth']
  end
end

app/controllers/pages_controller.rb
# frozen_string_literal: true

class PagesController < ApplicationController
  before_action :authenticate_user!, only: [:dashboard]
  def home
    redirect_to dashboard_path if current_user
  end

  def dashboard
    @scheduled = current_user.posts.where(state: 'scheduled')
                             .paginate(page: params[:scheduled_page],
                                       per_page: 2)
                             .order('scheduled_at ASC')
    @history = current_user.posts.where.not(state: 'scheduled')
                           .paginate(page: params[:history_page], per_page: 2)
                           .order('scheduled_at DESC')
  end
end

app/controllers/posts_controller.rb
# frozen_string_literal: true

class PostsController < ApplicationController
  before_action :set_post, only: [:cancel]

  def new
    if current_user.connections.any?
      @post = Post.new
    else
      redirect_to dashboard_path, notice: 'Please connect to a social network'
    end
  end

  def create
    @post = current_user.posts.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to dashboard_path, notice: 'post created successfully' }
      else
        format.html { render :new }
      end
    end
  end

  def cancel
    @post.update_attributes(state: 'canceled')
    redirect_to dashboard_path, notice: 'Post canceled'
  end

  private

  def set_post
    @post = Post.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:content, :scheduled_at, :state, :user_id, :facebook, :twitter)
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  private

  def sign_up_params
    params.require(:user).permit(:password, :email, :time_zone)
  end

  def account_update_params
    params.require(:user).permit(:name, :email, :time_zone, :current_password)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/connections_helper.rb
module ConnectionsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/connections/create.html.erb
<h1>Connections#create</h1>
<p>Find me in app/views/connections/create.html.erb</p>

app/views/connections/destroy.html.erb
<h1>Connections#destroy</h1>
<p>Find me in app/views/connections/destroy.html.erb</p>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default" role="navigation">
  <!-- Brand and toggle get grouped for better mobile display -->
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <%= link_to '<i class="fa fa-circle-o-notch"></i>Stukdo'.html_safe, root_path, class: 'navbar-brand' %>
  </div>

  <!-- Collect the nav links, forms, and other content for toggling -->
  <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
    <ul class="nav navbar-nav navbar-right">
      <% if current_user%>
        <li><%= link_to 'New Post', new_post_path %></li>
        <li><%= link_to 'Dashboard', dashboard_path%></li>
        <li><%= link_to 'Settings', edit_user_registration_path %></li>
        <li><%= link_to 'Log out', destroy_user_session_path, method: :delete %></li>
      <% else %>
        <li><%= link_to 'Log in', new_user_session_path %></li>
      <%end %>
    </ul>
  </div><!-- /.navbar-collapse -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Stuker</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "layouts/header" %>
    <% flash.each do |type, message| %>
      <div class="alert alert-info fade-in">
        <button type='button' aria-label="Close" class='close' data-dismiss="alert">x</button>
        <%= message%>
      </div>
    <%end%>
    <div class="container">

      <%= yield %>
    </div>
  </body>
</html>

app/views/pages/dashboard.html.erb
<div class="row">
  <div class="col-md-2 text-center">
    <%= image_tag 'img.jpeg', class: 'logo'%>
    <hr>
    <div class="timezone">
      <p class="text-center"><%= Time.zone.name %> Time Zone</p>
      <%= link_to 'change', edit_user_registration_path %>
      <hr>
      <div class="social">
        <% unless current_user.connections.where(provider: 'twitter').any? %>
          <%= link_to 'Connect With Twitter', '/auth/twitter', class: "btn btn-info btn-block btn-sm" %>
        <% else %>
          <%= link_to 'Destroy Twitter Connection', connection_path(current_user.connections.where(provider: 'twitter').first), method: :delete, class: "btn btn-info btn-block btn-sm" %>
        <%end %>

        <% unless current_user.connections.where(provider: 'facebook').any? %>
          <%= link_to 'Connect With Facebook', '/auth/facebook', class: "btn btn-primary btn-block btn-sm",  :disabled => true %>
        <% else %>
          <%= link_to 'destroy connection', connection_path(current_user.connections.where(provider: 'facebook').first), method: :delete, class: "btn btn-primary btn-block btn-sm" %>
        <%end %>
      </div>
    </div>
  </div>

  <div class="col-md-5 text-center">
    <h3>Shedule Post</h3>
    <hr>
    <%= render @scheduled %>
    <%= will_paginate @scheduled, :param_name => 'scheduled_page' %>
  </div>


  <div class="col-md-5 text-center">
    <h3>Post History</h3>
    <hr>
    <%= render @history %>
    <%= will_paginate @history, :param_name => 'history_page' %>
  </div>

</div>

app/views/pages/home.html.erb
<div class="text-center landing-title">
  <%= link_to 'The Freedom to post', new_user_session_path, class: 'btn btn-default btn-lg btn-landing'%>
</div>

app/views/posts/_form.html.erb
<%= simple_form_for(@post) do |f| %>

  <div class="form-imputs">
    <%= f.input :content, required: true, maxlength: 140%>
    <p>This post is sheduled at<b> <%= Time.zone.name %> time</b></p>
    <%= f.input :scheduled_at, required: true, as: :datetime_picker, input_html: {data: {date_options: {defaultDate: DateTime.now}}}  %>
  </div>

  <div class="form-inputs">
    <% if current_user.connections.where(provider: 'twitter').any? %>
      <%= f.input :twitter, required: true%>
    <% end %>

    <% if current_user.connections.where(provider: 'facebook').any? %>
      <%= f.input :facebook, required: true%>
    <% end %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>

<%end%>

app/views/posts/_post.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <span class="label label-primary">Twitter</span>
    Scheduled on <%= post.scheduled_at %>
  </div>

  <div class="panel-body">
    <%= post.content %>
  </div>

  <div class="panel-footer">
    <%= post.state%>
    <%= link_to 'Cancel', cancel_post_path(post), method: :put if post.state == 'scheduled' %>
  </div>
</div>

app/views/posts/new.html.erb
<h2>New Post</h2>

<%= render 'form' %>
<%= link_to 'back', dashboard_path %>